Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Data.SqlTypes;
using System.Web.Mvc;

namespace BookProject.Models
{
    public class Book
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        
        public string AuthorLastName { get; set; }

        
        public string AuthorFirstName { get; set; }

        public int PublicationYear { get; set; } = 2015;
        
        
        public string AuthorPlaceOfBirth { get; set; }

        [Required]
        public string Genre { get; set; }

        public string CoverImageFile { get; set; }
       
        public string UserId { get; set; }

        public string Latitude { get; set; }

        public string Longitude { get; set; }

        public string LatLong { get; set; }

        public bool AlreadyRead { get; set; }

        //foreign key
        public int AuthorId { get; set; }

        //navigation property
        public virtual Author Author { get; set; }


    }

    //public class BookDBContext : DbContext
    //{
    //    public DbSet<Book> Books { get; set; }
    //}

}

Models/ViewModels/ChartViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;

namespace BookProject.Models.ViewModels
{
    public class ChartViewModel
    {
        public ChartViewModel()
        {
             Chart = new Chart(600, 400);
        }
        public Chart Chart { get; set; }
    }
}








//namespace BookProject.Models.ViewModels
//{
//    public class ChartViewModel
//    {
//        public Chart Chart { get; set; }
//    }


//}

Models/ViewModels/StatsSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookProject.Models.ViewModels
{
    public class StatsSummaryViewModel
    {
        public StatsSummaryViewModel() 
        {
            StatsSummaryDictionary = new Dictionary<string, int>();
        }

        public Dictionary<string, int> StatsSummaryDictionary { get; set; }
}

    
}

Models/ViewModels/StatsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookProject.Models.ViewModels
{
    public class StatsViewModel
    {
        public StatsViewModel()
        {
            AuthorsDictionary = new Dictionary<string, string>();

            GenresDictionary = new Dictionary<string, string>();
        }

        public Dictionary<string, string> AuthorsDictionary { get; set; }

        public Dictionary<string, string> GenresDictionary { get; set; }




    }


}

Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BookProject.Models;

namespace BookProject.Controllers
{
    public class AuthorsController : Controller
    {
        private BookDBContext db = new BookDBContext();

        // GET: Authors
        public ActionResult Index()
        {

            //remember to copy this to book
            var authors = db.Authors.Include(a => a.Place);
            return View(authors.ToList());
        }

        // GET: Authors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // GET: Authors/Create
        public ActionResult Create()
        {
            ViewBag.PlaceId = new SelectList(db.Places, "Id", "PlaceName");
            return PartialView("_Create");
        }

        // POST: Authors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,PlaceId")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                //return RedirectToAction("Index");
            }

            ViewBag.PlaceId = new SelectList(db.Places, "Id", "PlaceName", author.PlaceId);
            return PartialView("_AuthorConfirm");
        }

        // GET: Authors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlaceId = new SelectList(db.Places, "Id", "PlaceName", author.PlaceId);
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,PlaceId")] Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PlaceId = new SelectList(db.Places, "Id", "PlaceName", author.PlaceId);
            return View(author);
        }

        // GET: Authors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using BookProject.Models;
using BookProject.Models.ViewModels;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Xml.Linq;
using BookProject.Migrations;

namespace BookProject.Controllers
{
    public class BooksController : Controller
    {
        private BookDBContext db = new BookDBContext();
        
        // GET: Books
        [Authorize]
        public ActionResult Index(string bookGenre, string searchString, string author)
        {
            var GenreLst = new List<string>();

            var GenreQry = from d in db.Books
                           orderby d.Genre
                           select d.Genre;

            

            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.bookGenre = new SelectList(GenreLst);


            var userId = User.Identity.GetUserId();
            var books = from b in db.Books.Where(b => b.UserId == userId)
                        select b;


            var AuthorList = new List<string>();

            foreach (var book in books)
            {
                string authorFull = book.AuthorFirstName + " " + book.AuthorLastName;

                if (!AuthorList.Contains(authorFull))
                {
                    AuthorList.Add(authorFull);
                }
            }

            ViewBag.author = new SelectList(AuthorList);

            if (!string.IsNullOrEmpty(author))
            {
                books = books.Where(x => (x.AuthorFirstName + " " + x.AuthorLastName) == author);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(bookGenre))
            {
                books = books.Where(x => x.Genre == bookGenre);
            }

            

            return View(books);
        }














        // GET: Books/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        [Authorize]
        public ActionResult Create()
        {
            var GenreLst = new List<SelectListItem>
            {
                    new SelectListItem {Text = "Action", Value = "Action"},
                    new SelectListItem {Text = "Adventure", Value = "Adventure"},
                    new SelectListItem {Text = "Art and design", Value = "Art and design"},
                    new SelectListItem {Text = "Autobiography", Value = "Autobiography"},
                    new SelectListItem {Text = "Biography", Value = "Biography"},
                    new SelectListItem {Text = "Business", Value = "Business"},
                    new SelectListItem {Text = "Childrens", Value = "Childrens"},
                    new SelectListItem {Text = "Classic literature", Value = "Classic literature"},
                    new SelectListItem {Text = "Comedy", Value = "Comedy"},
                    new SelectListItem {Text = "Comics and graphic novels", Value = "Comics and graphic novels"},
                    new SelectListItem {Text = "Computing", Value = "Computing"},
                    new SelectListItem {Text = "Cookery", Value = "Cookery"},
                    new SelectListItem {Text = "Craft and hobbies", Value = "Craft and hobbies"},
                    new SelectListItem {Text = "Crime", Value = "Crime"},
                    new SelectListItem {Text = "Dystopian fiction ", Value = "Dystopian fiction "},
                    new SelectListItem {Text = "Epic", Value = "Epic"},
                    new SelectListItem {Text = "Fantasy", Value = "Fantasy"},
                    new SelectListItem {Text = "Food and drink", Value = "Food and drink"},
                    new SelectListItem {Text = "Health", Value = "Health"},
                    new SelectListItem {Text = "Historical", Value = "Historical"},
                    new SelectListItem {Text = "Historical fiction", Value = "Historical fiction"},
                    new SelectListItem {Text = "Horror", Value = "Horror"},
                    new SelectListItem {Text = "Magical realism", Value = "Magical realism"},
                    new SelectListItem {Text = "Mystery", Value = "Mystery"},
                    new SelectListItem {Text = "Philosophical", Value = "Philosophical"},
                    new SelectListItem {Text = "Photography", Value = "Photography"},
                    new SelectListItem {Text = "Poetry", Value = "Poetry"},
                    new SelectListItem {Text = "Political", Value = "Political"},
                    new SelectListItem {Text = "Romance", Value = "Romance"},
                    new SelectListItem {Text = "Satire", Value = "Satire"},
                    new SelectListItem {Text = "Science fiction", Value = "Science fiction"},
                    new SelectListItem {Text = "Short story", Value = "Short story"},
                    new SelectListItem {Text = "Thriller", Value = "Thriller"},
                    new SelectListItem {Text = "Travel", Value = "Travel"},
                    new SelectListItem {Text = "Young adult", Value = "Young adult"},
                    new SelectListItem {Text = "Other", Value = "Other"},
            };

            ViewBag.bookGenre = GenreLst.ToList();


            var AuthorLst = new List<SelectListItem>();

            //var AuthorQry = from b in db.Books
            //                join a in db.Authors on b.AuthorId equals a.Id
            //                select new
            //                {
            //                    firstName = a.FirstName,
            //                    lastName = a.LastName,
            //                    id = a.Id
            //                };

            var AuthorQry = from a in db.Authors
                            select new
                            {
                                firstName = a.FirstName,
                                lastName = a.LastName,
                                id = a.Id
                            };

            foreach (var s in AuthorQry)
            {
                AuthorLst.Add(new SelectListItem {Text = (s.firstName + " " + s.lastName), Value = s.id.ToString()});
            }

            //AuthorLst.Add(new SelectListItem { Text = "Add new author", Value = "new" });

            ViewBag.bookAuthor = AuthorLst.ToList();



















            var YearLst = new List<SelectListItem>();

            for (var x = 2015; x >= -850; x--) {
                YearLst.Add(new SelectListItem{Text = x.ToString(), Value = x.ToString()});
            }

            ViewBag.bookYear = YearLst.ToList();

            var model = new Book();
        
            model.UserId = User.Identity.GetUserId();

            return View(model);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Title,AuthorLastName,AuthorFirstName,PublicationYear,AuthorId,AuthorPlaceOfBirth,Genre,CoverImage,UserId,AlreadyRead")] Book book, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    // extract only the filename
                    var fileName = Path.GetFileName(file.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                    file.SaveAs(path);

                    book.CoverImageFile = "/Images/" + fileName;
                }



                db.Books.Add(book);

                //coordinate setting
                //var requestUri = string.Format("http://maps.googleapis.com/maps/api/geocode/xml?address={0}&sensor=false", Uri.EscapeDataString(book.AuthorPlaceOfBirth));

                //var request = WebRequest.Create(requestUri);
                //var response = request.GetResponse();
                //var xdoc = XDocument.Load(response.GetResponseStream());

                //var result = xdoc.Element("GeocodeResponse").Element("result");
                //var locationElement = result.Element("geometry").Element("location");
                //var lat = locationElement.Element("lat");
                //var lng = locationElement.Element("lng");

                //var latString = lat.ToString().Replace("<lat>", "").Replace("</lat>", "");

                //var lngString = lng.ToString().Replace("<lng>", "").Replace("</lng>", "");

                //book.Latitude = latString;
                //book.Longitude = lngString;

                db.SaveChanges();
      
                return RedirectToAction("Index");
            }

            return View(book);
        }




        // GET: Books/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }

            var GenreLst = new List<SelectListItem>
            {

Views/Books/CreateBook.cshtml
@using BookProject.Controllers
@using Microsoft.AspNet.Identity
@model BookProject.Models.Book
@Styles.Render("~/Content/themes/base/css")
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryui")

@{
    ViewBag.Title = "Add new book";
}

<h1><img src="@Url.Content("/Images/book.png")" width="30" /> Add a new book</h1>


@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "e.g. The Lion, the Witch and the Wardrobe" }})
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorFirstName, "Author's first name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorFirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "e.g. C.S or Clive" } })
                @Html.ValidationMessageFor(model => model.AuthorFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorLastName, "Author's last name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorLastName, new { htmlAttributes = new { @class = "form-control", placeholder = "e.g. Lewis" } })
                @Html.ValidationMessageFor(model => model.AuthorLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublicationYear, "Publication year", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PublicationYear, new SelectList(ViewBag.bookYear, "Value", "Text"))
                @*@Html.EditorFor(model => model.PublicationYear, new {htmlAttributes = new {@class = "form-control", placeholder = "e.g. 1950"}})*@
                @Html.ValidationMessageFor(model => model.PublicationYear, "", new {@class = "text-danger"})
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.AuthorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorPlaceOfBirth, "Author's place of birth", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorPlaceOfBirth, new { htmlAttributes = new { @class = "form-control", placeholder = "e.g. York, England" } })
                @Html.ValidationMessageFor(model => model.AuthorPlaceOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.Genre, new SelectList(ViewBag.bookGenre, "Value", "Text"), "Select one")
                    
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoverImageFile, "Cover image", htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CoverImageFile, new {htmlAttributes = new {@class = "form-control", placeholder = "e.g. C:/Users/lkey/Pictures/BoneClocks.jpg" } })
                @Html.ValidationMessageFor(model => model.CoverImageFile, "", new {@class = "text-danger"})*@

                @*<p>test upload</p>
                <p><strong>@Html.ActionLink("Upload Image", "ImageUpload")</strong></p>*@


                @*<input type="text" name="imageId" id="imageId" />*@
                @*<button type="button" id="refreshButton">Update Image</button>*@
                @*<img src="/" style="display: none" id="preview" />*@


                <input type="file" name="file"/>
                @*byte[] bytes = System.IO.File.ReadAllBytes(filename);*@

                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AlreadyRead, "I've read it", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AlreadyRead)
                @Html.ValidationMessageFor(model => model.AlreadyRead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default"/>
                @Html.HiddenFor(model => model.UserId)
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to my books", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Books/Delete.cshtml
@model BookProject.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h1><img src="@Url.Content("/Images/book.png")" width="30" /> Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            Author's first name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorFirstName)
        </dd>

        <dt>
            Author's last name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorLastName)
        </dd>

        <dt>
            Publication year
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublicationYear)
        </dd>

        <dt>
            Author's place of birth
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorPlaceOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Books/ImageGrid.cshtml
@model IEnumerable<BookProject.Models.Book>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@foreach (var item in Model)
{
    <tr>
        <td>
            @{
                var img = "/Images/DefaultBook.jpg";

                if (item.CoverImageFile != null)
                {
                    img = @Url.Content(item.CoverImageFile);
                }
                else
                {
                    img = "/Images/DefaultBook.jpg";
                }

                var i = 0;
                if (i % 3 == 0)
                {
                    Html.Raw("</tr><tr>"); //End old row and start new one
                }
                i++;
            }
            <img src='@img' width="100" />
        </td>
    </tr>
                }

Views/Books/Index.cshtml
@model IEnumerable<BookProject.Models.Book>

@{
    ViewBag.Title = "My Books";
}

<h1><img src="@Url.Content("/Images/book.png")" width="30" /> My Books</h1>

<p><strong>@Html.ActionLink("View my stats", "MyStatsView")</strong><br/>
   <strong>@Html.ActionLink("Cover gallery", "ImageGrid")</strong>
</p>

@*<p><strong>@Html.ActionLink("View chart", "Chart")</strong>
</p>
<p><strong>@Html.ActionLink("View timeline", "Timeline")</strong></p>*@


<h4>Search by author, title and genre</h4>

<p>@using (Html.BeginForm("Index", "Books", FormMethod.Get)){
       <p>
           Author: @Html.DropDownList("author", "All") <br />
           Title: @Html.TextBox("SearchString") <br/>
           Genre: @Html.DropDownList("bookGenre", "All") <br />
           <input type="submit" value="Filter"/>
       </p>
        }
</p>        

 <p><strong>@Html.ActionLink("Add book", "Create")</strong></p>

<table class="table">

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.CoverImageFile != null)
            {
                <img src="@Url.Content(item.CoverImageFile)" alt="Image" width="200"/>
            }
            else
            {
                <img src="/Images/DefaultBook.jpg" alt="Image" width="200" />
            }
        </td>
        <td>
            <strong>@Html.ActionLink((Html.DisplayTextFor(modelItem => item.Title).ToString()).Replace("&#39;", "'"), "Details", new { id = item.Id })</strong>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuthorFirstName) @Html.DisplayFor(modelItem => item.AuthorLastName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new {id = item.Id})
        </td>
    </tr>
    
}
    <strong>@Html.ActionLink("View your book map", "MapView")</strong>




    



</table>

Views/Books/MapView.cshtml
@*@model BookProject.Models.Book *@
@model IEnumerable<BookProject.Models.Book>
< !DOCTYPE html >
<html>
<head>
    <style>
        #map_canvas {
            width: 100%;
            height: 600px;
            background-color: #CCC;
        }
    </style>
    
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script>

        var geocoder;
        var map;





        function initialize() {


            var latlng = new google.maps.LatLng(51.4500, -2.5833);
            var myOptions = {
                zoom: 2,
                center: latlng,
                mapTypeControl: true,
                mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
                },
                navigationControl: true,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };


            map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);

            var locations = [@Html.Raw(ViewBag.coords)];
            var titles = [@Html.Raw(ViewBag.titles)];
            var ids = [@Html.Raw(ViewBag.ids)];
            var infowindow = new google.maps.InfoWindow();
            var marker, i;
            var image = '/Images/book.png';

            for (i = 0; i < locations.length; i++) {

                marker = new google.maps.Marker({
                    position: new google.maps.LatLng(locations[i][0], locations[i][1]),
                    map: map,
                    icon: image,
                    //title: titles[i].toString()
                    ID: ids[i].toString(),
                    title: titles[i].toString()

            });

                //var titleString = titles[i].toString();

                //window = new new google.maps.InfoWindow();
                //window.setContent("book");
                //window.open(map, marker);

                google.maps.event.addListener(marker, 'click', (function(marker) {
                    return function() {
                        //infowindow.setContent(marker.title);
                        var Id = marker.ID;

                        @*infowindow.setContent(@Url.Action("Details", "Details", new $.({ id = marker.title })));*@
                        @*infowindow.setContent(@Url.Action("Index", "Books"));*@
                        @*infowindow.setContent('@Html.ActionLink("Back to List", "Details", )');*@

                        var linklabel = marker.title;
                        //not good...but works for now
                        var linkStringTemp = "http://localhost:49777/Books/Details/CHANGE";
                        var linkString = linkStringTemp.replace("CHANGE", Id);
                        var result = linklabel.link(linkString);
                        infowindow.setContent(result);

                        //+ '?' + $.param({ id: Id })
                        infowindow.open(map, marker);
                        }
                    })(marker));
            }
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    </script>
</head>
<body style="margin:20px; padding:0px;" onload="initialize()">
<h2> </h2>
<h2> </h2>
<h1><img src="@Url.Content("/Images/book.png")" width="30" /> Your Book Map</h1>
    <div id="map_canvas"></div>
</body>
</html>

Views/Books/TESTVIEW.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<script src="/Scripts/MicrosoftAjax.js" type="text/javascript"></script>
<script src="/Scripts/MicrosoftMvcAjax.js" type="text/javascript"></script>*@
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>


<h2>This is an ajax test</h2>



@Ajax.ActionLink("Load partial view", "Create", "Authors", new AjaxOptions
{
    //JavaScript function executed after successful Ajax request
    //OnSuccess = "updatePlaceholder",
    //The "id" attribute of the HTML placeholder
    UpdateTargetId = "result"
})



<div id="result"></div>

@*<script type="text/javascript">
   function updatePlaceholder(context) {
        // the HTML output of the partial view
        var html = context.get_data();

        // the DOM element representing the placeholder
        var placeholder = context.get_updateTarget();

        // use jQuery to update the placeholder. It will execute any JavaScript statements
        $(placeholder).html(html);

        // return false to prevent the automatic update of the placeholder
        return false;
    }
</script>*@



@*$.ajax({
    url: '@Url.Action("TestPartial", "Books")',


    });*@

Views/Books/ViewPage1.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}